export const CHANGE_DEADLINE='CHANGE_DEADLINE';
export const CHANGE_PROGRESS_COLOR='CHANGE_PROGRESS_COLOR';
export const CHANGE_BACKGROUND_RING_COLOR='CHANGE_BACKGROUND_RING_COLOR';
export const CHANGE_BACKGROUND='CHANGE_BACKGROUND';
export const CHANGE_COUNTDOWN_NAME= 'CHANGE_COUNTDOWN_NAME';
export const CHANGE_TEXT_COLOR = 'CHANGE_TEXT_COLOR';